[features]
seeds = false
skip-lint = false
[programs.localnet]
solcare = "DqBjFvgYa8drGBcKdSSQ51jLEWWnr6z14MzXKxGu5JvX"
[programs.devnet]
solcare = "DqBjFvgYa8drGBcKdSSQ51jLEWWnr6z14MzXKxGu5JvX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/nathanramli/.config/solana/id.json"

[scripts]
# Run `anchor test tests/*.spec.ts`
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000"
